// Code generated by "stringer -type=AccessType --trimprefix=Access"; DO NOT EDIT.

package gitserver

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AccessRead-0]
	_ = x[AccessWrite-1]
}

const _AccessType_name = "ReadWrite"

var _AccessType_index = [...]uint8{0, 4, 9}

func (i AccessType) String() string {
	if i < 0 || i >= AccessType(len(_AccessType_index)-1) {
		return "AccessType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AccessType_name[_AccessType_index[i]:_AccessType_index[i+1]]
}
